################################################################
## Packages / Dog Mode
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'dog_mode'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Input Boolean
    ################################################
    
    input_boolean.dogs_home:
      <<: *customize
      friendly_name: "Are the dogs at home?"
      icon: mdi:dog-side
      persistent: true

################################################
## Input Boolean
################################################

input_boolean:
  dogs_home:
    initial: on