homeassistant:
  name: !secret home_name
  latitude: !secret home_lat
  longitude: !secret home_long
  elevation: !secret home_elevation
  unit_system: metric
  time_zone: !secret home_time_zone
  customize: !include customize.yaml

frontend:

config:

http:
  api_password: !secret http_password
  base_url: !secret http_base_url 

updater:

discovery:

conversation:

history:

logbook:

map:

sun:

tts:
  - platform: google

cloud:

#begin two hunnid crap
vera:
  vera_controller_url: http://192.168.1.191:3480/
  exclude: []
  # Optional to import switches as lights - this is a list of vera device ids
  lights: [19,28,27]
  
nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret
  
light:
  - platform: x10
    devices:
      - id: b2
        name: Backyard String Lights

sensor:
  - platform: yr
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /home
      - type: memory_use_percent
      - type: load_5m
      - type: since_last_boot
      
#includes	  
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
