homeassistant:
  name: !secret home_name
  latitude: !secret home_lat
  longitude: !secret home_long
  elevation: !secret home_elevation
  unit_system: metric
  time_zone: !secret home_time_zone
  customize: !include customize.yaml

frontend:

config:

http:
  api_password: !secret http_password
  base_url: !secret http_base_url 

updater:

discovery:

conversation:

history:

logbook:

map:

sun:

tts:
  - platform: google

cloud:

mqtt:
  broker: 192.168.1.19

#begin two hunnid crap
vera:
  vera_controller_url: http://192.168.1.191:3480/
  exclude: []
  # Optional to import switches as lights - this is a list of vera device ids
  lights: [19,27]
  
nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret
  
light:
  - platform: x10
    devices:
      - id: b2
        name: String Lights

sensor:
  - platform: yr
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /home
      - type: memory_use_percent
      - type: load_5m
      - type: since_last_boot
  ##### PLANTS #####
  #### PLANTS - zebra plant ####
  - platform: mqtt
    state_topic: "twohunnidha/sensors/plants/zebra_plant/"
    name: plant_zebra_plant
    value_template: "{{ value_json.moisture }}"
    json_attributes:
      - battery
      - moisture
      - temperature
      - brightness
      - timestamp
      - conductivity
  - platform: template
    sensors:
      plant_zebra_plant_battery:
        friendly_name: "Zebra Plant - Battery"
        entity_id: sensor.plant_zebra_plant
        value_template: "{{ states.sensor.plant_zebra_plant.attributes.battery }}"
        device_class: battery
        unit_of_measurement: '%'
      plant_zebra_plant_moisture:
        friendly_name: "Zebra Plant - Moisture"
        entity_id: sensor.plant_zebra_plant
        unit_of_measurement: '%'
        value_template: "{{ states.sensor.plant_zebra_plant.attributes.moisture }}"
      plant_zebra_plant_temperature:
        friendly_name: "Zebra Plant - Temperature"
        entity_id: sensor.plant_zebra_plant
        unit_of_measurement: '°F'
        value_template: >
          {{ ((float(state_attr('sensor.plant_zebra_plant', 'temperature')) * 9 /5)+32)|round(1) }}
      plant_zebra_plant_brightness:
        friendly_name: "Zebra Plant - Brightness"
        entity_id: sensor.plant_zebra_plant
        value_template: "{{ states.sensor.plant_zebra_plant.attributes.brightness }}"
      plant_zebra_plant_conductivity:
        friendly_name: "Zebra Plant - Conductivity"
        entity_id: sensor.plant_zebra_plant
        unit_of_measurement: 'µS/cm'
        value_template: "{{ states.sensor.plant_zebra_plant.attributes.conductivity }}"
        
  #### PLANTS - desert rose ####
  - platform: mqtt
    state_topic: "twohunnidha/sensors/plants/desert_rose/"
    name: plant_desert_rose
    value_template: "{{ value_json.moisture }}"
    json_attributes:
      - battery
      - moisture
      - temperature
      - brightness
      - timestamp
      - conductivity
  - platform: template
    sensors:
      plant_desert_rose_battery:
        friendly_name: "Desert Rose - Battery"
        entity_id: sensor.plant_desert_rose
        value_template: "{{ states.sensor.plant_desert_rose.attributes.battery }}"
        device_class: battery
        unit_of_measurement: '%'
      plant_desert_rose_moisture:
        friendly_name: "Desert Rose - Moisture"
        entity_id: sensor.plant_desert_rose
        unit_of_measurement: '%'
        value_template: "{{ states.sensor.plant_desert_rose.attributes.moisture }}"
      plant_desert_rose_temperature:
        friendly_name: "Desert Rose - Temperature"
        entity_id: sensor.plant_desert_rose
        unit_of_measurement: '°F'
        value_template: >
          {{ ((float(state_attr('sensor.plant_desert_rose', 'temperature')) * 9 /5)+32)|round(1) }}
      plant_desert_rose_brightness:
        friendly_name: "Desert Rose - Brightness"
        entity_id: sensor.plant_desert_rose
        value_template: "{{ states.sensor.plant_desert_rose.attributes.brightness }}"
      plant_desert_rose_conductivity:
        friendly_name: "Desert Rose - Conductivity"
        entity_id: sensor.plant_desert_rose
        unit_of_measurement: 'µS/cm'
        value_template: "{{ states.sensor.plant_desert_rose.attributes.conductivity }}"
        
plant:
  zebra_plant:
    sensors:
      moisture: sensor.plant_zebra_plant_moisture
      battery: sensor.plant_zebra_plant_battery
      temperature: sensor.plant_zebra_plant_temperature
      conductivity: sensor.plant_zebra_plant_conductivity
      brightness: sensor.plant_zebra_plant_brightness
    min_moisture: 20
    max_moisture: 60
    min_battery: 17
    min_conductivity: 350
    min_temperature: 15
    max_temperature: 30
  desert_rose:
    sensors:
      moisture: sensor.plant_desert_rose_moisture
      battery: sensor.plant_desert_rose_battery
      temperature: sensor.plant_desert_rose_temperature
      conductivity: sensor.plant_desert_rose_conductivity
      brightness: sensor.plant_desert_rose_brightness
    min_moisture: 20
    max_moisture: 60
    min_battery: 17
    min_conductivity: 350
    min_temperature: 15
    max_temperature: 30
      
#includes  
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
