homeassistant:
  name: !secret home_name
  latitude: !secret home_lat
  longitude: !secret home_long
  elevation: !secret home_elevation
  unit_system: metric
  time_zone: !secret home_time_zone
  customize: !include customize.yaml

frontend:

config:

http:
  api_password: !secret http_password
  base_url: !secret http_base_url 

updater:

discovery:

conversation:

history:

logbook:

map:

sun:

telegram_bot:
  - platform: webhooks
    api_key: !secret telegram_bot_key
    parse_mode: html
    trusted_networks:
      - 149.154.167.197/32
      - 149.154.167.198/31
      - 149.154.167.200/29
      - 149.154.167.208/28
      - 149.154.167.224/29
      - 149.154.167.232/31
      - !secret http_reverse_proxy_ip
    allowed_chat_ids:
      - !secret telegram_bot_chat_id_1

tts:
  - platform: google

cloud:

mqtt:
  broker: 192.168.1.19

#begin two hunnid crap
vera:
  vera_controller_url: http://192.168.1.191:3480/
  exclude: []
  # Optional to import switches as lights - this is a list of vera device ids
  lights: [19,27]

zwave:
  usb_path: /dev/ttyACM0
  config_path: /srv/homeassistant/lib/python3.5/site-packages/python_openzwave/ozw_config
  network_key: !secret zwave_network_key
  
nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret
  
light:
  - platform: x10
    devices:
      - id: b2
        name: String Lights

sensor:
  - platform: yr
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /home
      - type: memory_use_percent
      - type: load_5m
      - type: since_last_boot
  ##### PLANTS #####
  #### PLANTS - zebra plant ####
  - platform: mqtt
    state_topic: "twohunnidha/sensors/plants/zebra_plant/"
    name: plant_zebra_plant
    value_template: "{{ value_json.moisture }}"
    json_attributes:
      - battery
      - moisture
      - temperature
      - brightness
      - timestamp
      - conductivity
  - platform: template
    sensors:
      plant_zebra_plant_battery:
        friendly_name: "Zebra Plant - Battery"
        entity_id: sensor.plant_zebra_plant
        value_template: "{{ states.sensor.plant_zebra_plant.attributes.battery }}"
        device_class: battery
        unit_of_measurement: '%'
      plant_zebra_plant_moisture:
        friendly_name: "Zebra Plant - Moisture"
        entity_id: sensor.plant_zebra_plant
        unit_of_measurement: '%'
        value_template: "{{ states.sensor.plant_zebra_plant.attributes.moisture }}"
      plant_zebra_plant_temperature:
        friendly_name: "Zebra Plant - Temperature"
        entity_id: sensor.plant_zebra_plant
        unit_of_measurement: '°F'
        value_template: >
          {{ ((float(state_attr('sensor.plant_zebra_plant', 'temperature')) * 9 /5)+32)|round(1) }}
      plant_zebra_plant_brightness:
        friendly_name: "Zebra Plant - Brightness"
        entity_id: sensor.plant_zebra_plant
        value_template: "{{ states.sensor.plant_zebra_plant.attributes.brightness }}"
      plant_zebra_plant_conductivity:
        friendly_name: "Zebra Plant - Conductivity"
        entity_id: sensor.plant_zebra_plant
        unit_of_measurement: 'µS/cm'
        value_template: "{{ states.sensor.plant_zebra_plant.attributes.conductivity }}"
        
  #### PLANTS - desert rose ####
  - platform: mqtt
    state_topic: "twohunnidha/sensors/plants/desert_rose/"
    name: plant_desert_rose
    value_template: "{{ value_json.moisture }}"
    json_attributes:
      - battery
      - moisture
      - temperature
      - brightness
      - timestamp
      - conductivity
  - platform: template
    sensors:
      plant_desert_rose_battery:
        friendly_name: "Desert Rose - Battery"
        entity_id: sensor.plant_desert_rose
        value_template: "{{ states.sensor.plant_desert_rose.attributes.battery }}"
        device_class: battery
        unit_of_measurement: '%'
      plant_desert_rose_moisture:
        friendly_name: "Desert Rose - Moisture"
        entity_id: sensor.plant_desert_rose
        unit_of_measurement: '%'
        value_template: "{{ states.sensor.plant_desert_rose.attributes.moisture }}"
      plant_desert_rose_temperature:
        friendly_name: "Desert Rose - Temperature"
        entity_id: sensor.plant_desert_rose
        unit_of_measurement: '°F'
        value_template: >
          {{ ((float(state_attr('sensor.plant_desert_rose', 'temperature')) * 9 /5)+32)|round(1) }}
      plant_desert_rose_brightness:
        friendly_name: "Desert Rose - Brightness"
        entity_id: sensor.plant_desert_rose
        value_template: "{{ states.sensor.plant_desert_rose.attributes.brightness }}"
      plant_desert_rose_conductivity:
        friendly_name: "Desert Rose - Conductivity"
        entity_id: sensor.plant_desert_rose
        unit_of_measurement: 'µS/cm'
        value_template: "{{ states.sensor.plant_desert_rose.attributes.conductivity }}"
        
  #### PLANTS - peace_lily ####
  - platform: mqtt
    state_topic: "twohunnidha/sensors/plants/peace_lily/"
    name: plant_peace_lily
    value_template: "{{ value_json.moisture }}"
    json_attributes:
      - battery
      - moisture
      - temperature
      - brightness
      - timestamp
      - conductivity
  - platform: template
    sensors:
      plant_peace_lily_battery:
        friendly_name: "Peace Lily - Battery"
        entity_id: sensor.plant_peace_lily
        value_template: "{{ states.sensor.plant_peace_lily.attributes.battery }}"
        device_class: battery
        unit_of_measurement: '%'
      plant_peace_lily_moisture:
        friendly_name: "Peace Lily - Moisture"
        entity_id: sensor.plant_peace_lily
        unit_of_measurement: '%'
        value_template: "{{ states.sensor.plant_peace_lily.attributes.moisture }}"
      plant_peace_lily_temperature:
        friendly_name: "Peace Lily - Temperature"
        entity_id: sensor.plant_peace_lily
        unit_of_measurement: '°F'
        value_template: >
          {{ ((float(state_attr('sensor.plant_peace_lily', 'temperature')) * 9 /5)+32)|round(1) }}
      plant_peace_lily_brightness:
        friendly_name: "Peace Lily - Brightness"
        entity_id: sensor.plant_peace_lily
        value_template: "{{ states.sensor.plant_peace_lily.attributes.brightness }}"
      plant_peace_lily_conductivity:
        friendly_name: "Peace Lily - Conductivity"
        entity_id: sensor.plant_peace_lily
        unit_of_measurement: 'µS/cm'
        value_template: "{{ states.sensor.plant_peace_lily.attributes.conductivity }}"
        
  #### PLANTS - lemon_verbena ####
  - platform: mqtt
    state_topic: "twohunnidha/sensors/plants/lemon_verbena/"
    name: plant_lemon_verbena
    value_template: "{{ value_json.moisture }}"
    json_attributes:
      - battery
      - moisture
      - temperature
      - brightness
      - timestamp
      - conductivity
  - platform: template
    sensors:
      plant_lemon_verbena_battery:
        friendly_name: "Lemon Verbena - Battery"
        entity_id: sensor.plant_lemon_verbena
        value_template: "{{ states.sensor.plant_lemon_verbena.attributes.battery }}"
        device_class: battery
        unit_of_measurement: '%'
      plant_lemon_verbena_moisture:
        friendly_name: "Lemon Verbena - Moisture"
        entity_id: sensor.plant_lemon_verbena
        unit_of_measurement: '%'
        value_template: "{{ states.sensor.plant_lemon_verbena.attributes.moisture }}"
      plant_lemon_verbena_temperature:
        friendly_name: "Lemon Verbena - Temperature"
        entity_id: sensor.plant_lemon_verbena
        unit_of_measurement: '°F'
        value_template: >
          {{ ((float(state_attr('sensor.plant_lemon_verbena', 'temperature')) * 9 /5)+32)|round(1) }}
      plant_lemon_verbena_brightness:
        friendly_name: "Lemon Verbena - Brightness"
        entity_id: sensor.plant_lemon_verbena
        value_template: "{{ states.sensor.plant_lemon_verbena.attributes.brightness }}"
      plant_lemon_verbena_conductivity:
        friendly_name: "Lemon Verbena - Conductivity"
        entity_id: sensor.plant_lemon_verbena
        unit_of_measurement: 'µS/cm'
        value_template: "{{ states.sensor.plant_lemon_verbena.attributes.conductivity }}"
        
plant: !include_dir_named configuration/plant/

history_graph:
  plant_moisture:
    name: Plant Moisture
    entities:
      - sensor.plant_zebra_plant_moisture
      - sensor.plant_desert_rose_moisture
      - sensor.plant_peace_lily_moisture
      - sensor.plant_lemon_verbena_moisture
    hours_to_show: 120
    refresh: 60
      
#includes  
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
notify: !include notify.yaml
alert: !include alerts.yaml