homeassistant:
  name: !secret home_name
  latitude: !secret home_lat
  longitude: !secret home_long
  elevation: !secret home_elevation
  unit_system: imperial
  time_zone: !secret home_time_zone
  customize: !include customize.yaml

frontend:

config:

http:
  api_password: !secret http_password
  base_url: !secret http_base_url 

updater:

discovery:

conversation:

history:

logbook:

map:

sun:

alarm_control_panel: !include configuration/alarm.yaml

telegram_bot:
  - platform: webhooks
    api_key: !secret telegram_bot_key
    parse_mode: html
    trusted_networks:
      - 149.154.167.197/32
      - 149.154.167.198/31
      - 149.154.167.200/29
      - 149.154.167.208/28
      - 149.154.167.224/29
      - 149.154.167.232/31
      - !secret http_reverse_proxy_ip
    allowed_chat_ids:
      - !secret telegram_bot_chat_id_1

tts:
  - platform: google

cloud:

mqtt:
  broker: 192.168.1.19

#begin two hunnid crap
vera:
  vera_controller_url: http://192.168.1.191:3480/
  exclude: []
  # Optional to import switches as lights - this is a list of vera device ids
  lights: [19,27]

zwave:
  usb_path: /dev/ttyACM0
  config_path: /srv/homeassistant/lib/python3.5/site-packages/python_openzwave/ozw_config
  network_key: !secret zwave_network_key
  
nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret
  
light:
  - platform: x10
    devices:
      - id: b2
        name: String Lights

sensor: !include_dir_merge_list configuration/sensors/
binary_sensor: !include_dir_merge_list configuration/binary_sensors/

plant: !include_dir_named configuration/plant/

history_graph:
  plant_moisture:
    name: Plant Moisture
    entities:
      - sensor.plant_zebra_plant_moisture
      - sensor.plant_desert_rose_moisture
      - sensor.plant_peace_lily_moisture
      - sensor.plant_lemon_verbena_moisture
    hours_to_show: 120
    refresh: 60
      
#includes  
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
notify: !include notify.yaml
alert: !include alerts.yaml