homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'backyard_camera'
    
    camera.yi_home_camera_backyard_patio:
      <<: *customize
      friendly_name: "Backyard Patio Camera"
      icon: mdi:cctv
    
    binary_sensor.backyard_patio_camera_motion:
      <<: *customize
      friendly_name: "Motion - Backyard Patio (Camera)"
      camera_entity_id: "yi_home_camera_backyard_patio"
      
    binary_sensor.backyard_patio_camera_status:
      <<: *customize
      friendly_name: "Backyard Patio Camera Status"
      device_class: connectivity

camera:
  - platform: ffmpeg
    name: yi_home_camera_backyard_patio
    input: -rtsp_transport tcp -i rtsp://192.168.1.71:554/ch0_1.h264
    
binary_sensor:
  - platform: template
    sensors:
      backyard_patio_camera_motion:
        entity_id: sensor.yi_camera_motion_backyard
        device_class: motion
        value_template: "{{ states('sensor.yi_camera_motion_backyard')|int == 1 }}"
  - platform: ping
    name: backyard_patio_camera_status
    host: 192.168.1.71
    count: 3
    scan_interval: 60