
homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'ballet_studio_camera'
    
    camera.yi_home_camera_ballet_studio_camera:
      <<: *customize
      friendly_name: "Ballet Studio Camera"
      icon: mdi:cctv
    
    binary_sensor.ballet_studio_camera_motion:
      <<: *customize
      friendly_name: "Motion - Ballet Studio (Camera)"
      camera_entity_id: "yi_home_camera_ballet_studio_camera"
      
    binary_sensor.ballet_studio_camera_status:
      <<: *customize
      friendly_name: "Ballet Studio Camera Status"
      device_class: connectivity

camera:
  - platform: ffmpeg
    name: yi_home_camera_ballet_studio_camera
    input: -rtsp_transport tcp -i rtsp://192.168.1.73:554/ch0_1.h264
    
binary_sensor:
  - platform: template
    sensors:
      ballet_studio_camera_motion:
        entity_id: sensor.yi_camera_motion_ballet
        device_class: motion
        value_template: "{{ states('sensor.yi_camera_motion_ballet')|int == 1 }}"
  - platform: ping
    name: ballet_studio_camera_status
    host: 192.168.1.73
    count: 3
    scan_interval: 60