################################################################
## Packages / Backyard Camera
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'garage_camera'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Camera
    ################################################
    
    camera.yi_home_camera_garage:
      <<: *customize
      friendly_name: "Garage Camera"
      icon: mdi:cctv
    
    binary_sensor.garage_camera_motion:
      <<: *customize
      friendly_name: "Motion - Garage (Camera)"
      camera_entity_id: "yi_home_camera_garage"

camera:
  - platform: ffmpeg
    name: yi_home_camera_garage
    input: -rtsp_transport tcp -i rtsp://192.168.1.72:554/ch0_1.h264
    
binary_sensor:
  - platform: template
    sensors:
      garage_camera_motion:
        entity_id: sensor.yi_camera_motion_garage
        device_class: motion
        value_template: "{{ states('sensor.yi_camera_motion_garage')|int == 1 }}"