- platform: template
  sensors:
    motion_backyard_north:
      friendly_name: "Motion - Backyard (North)"
      device_class: motion
      value_template: "{{ states('sensor.vision_zp3102_pir_motion_sensor_alarm_level')|int == 255 }}"