- platform: template
  sensors:
    motion_front_yard_south:
      friendly_name: "Motion - Front Yard (South)"
      entity_id: sensor.vision_zp3102_pir_motion_sensor_alarm_level_3
      device_class: motion
      value_template: "{{ states('sensor.vision_zp3102_pir_motion_sensor_alarm_level_3')|int == 255 }}"