homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'motion_backyard_north'
    
    binary_sensor.motion_backyard_north:
      <<: *customize
      friendly_name: "Motion - Backyard (North)"
      device_class: motion
      
    sensor.device_motion_backyard_north_battery:
      <<: *customize
      friendly_name: "Motion - Backyard (North) - Battery"
      device_class: battery
      unit_of_measurement: '%'
      
     
binary_sensor:
  - platform: template
    sensors:
      motion_backyard_north:
        entity_id: sensor.vision_zp3102_pir_motion_sensor_alarm_level
        value_template: "{{ states('sensor.vision_zp3102_pir_motion_sensor_alarm_level')|int == 255 }}"
        
sensor:
  - platform: template
    sensors:
      device_motion_backyard_north_battery:
        entity_id: zwave.vision_zp3102_pir_motion_sensor
        value_template: "{{ state_attr('zwave.vision_zp3102_pir_motion_sensor','battery_level') }}"