- platform: template
  sensors:
    motion_backyard_south:
      friendly_name: "Motion - Backyard (South)"
      entity_id: sensor.vision_zp3102_pir_motion_sensor_alarm_level_2
      device_class: motion
      value_template: "{{ states('sensor.vision_zp3102_pir_motion_sensor_alarm_level_2')|int == 255 }}"
      
homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'motion_backyard_south'
    
    binary_sensor.motion_backyard_south:
      <<: *customize
      friendly_name: "Motion - Backyard (South)"
      device_class: motion
      
    sensor.device_motion_backyard_south_battery:
      <<: *customize
      friendly_name: "Motion - Backyard (South) - Battery"
      device_class: battery
      unit_of_measurement: '%'
      
     
binary_sensor:
  - platform: template
    sensors:
      motion_backyard_south:
        entity_id: sensor.vision_zp3102_pir_motion_sensor_alarm_level_2
        value_template: "{{ states('sensor.vision_zp3102_pir_motion_sensor_alarm_level_2')|int == 255 }}"
        
sensor:
  - platform: template
    sensors:
      device_motion_backyard_south_battery:
        entity_id: zwave.vision_zp3102_pir_motion_sensor_2
        value_template: "{{ state_attr('zwave.vision_zp3102_pir_motion_sensor_2','battery_level') }}"