################################################################
## Packages / desert_rose
################################################################

homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'plant_desert_rose'
      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false
        
    plant.desert_rose:
      <<: *customize
      friendly_name: Desert Rose
      
    sensor.plant_desert_rose_battery:
      <<: *customize
      friendly_name: "Desert Rose - Battery"
      device_class: battery
      unit_of_measurement: '%'
      
    sensor.plant_desert_rose_moisture:
      <<: *customize
      friendly_name: "Desert Rose - Moisture"
      unit_of_measurement: '%'
      
    sensor.plant_desert_rose_temperature:
      <<: *customize
      friendly_name: "Desert Rose - Temperature"
      unit_of_measurement: '°F'
        
    sensor.plant_desert_rose_brightness:
      <<: *customize
      friendly_name: "Desert Rose - Brightness"
      unit_of_measurement: 'lux'
      
    sensor.plant_desert_rose_conductivity:
      <<: *customize
      friendly_name: "Desert Rose - Conductivity"
      unit_of_measurement: 'µS/cm'
    
        
        
plant:
  desert_rose:
    sensors:
      moisture: sensor.plant_desert_rose_moisture
      battery: sensor.plant_desert_rose_battery
      temperature: sensor.plant_desert_rose_temperature
      conductivity: sensor.plant_desert_rose_conductivity
      brightness: sensor.plant_desert_rose_brightness
    min_moisture: 25
    max_moisture: 80
    min_battery: 15
    min_conductivity: 250
    min_temperature: 40
    max_temperature: 90
        
automation:
  - id: desert_rose_notify_problems
    alias: 'Desert Rose Notify of Problems'
    trigger:
    - entity_id: plant.desert_rose
      platform: state
      to: problem
    condition: []
    action:
    - data_template:
        message: "Desert Rose has an issue: {{ trigger.to_state.attributes.problem }}. Moisture: {{ trigger.to_state.attributes.moisture }}% Temp: {{ trigger.to_state.attributes.temperature }} Conductivity: {{ trigger.to_state.attributes.conductivity }}"
      service: notify.nick