################################################################
## Packages / fiddle_leaf_fig
################################################################

homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'plant_fiddle_leaf_fig'
      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false
        
    plant.fiddle_leaf_fig:
      <<: *customize
      friendly_name: Fiddle Leaf Fig
      
    sensor.plant_fiddle_leaf_fig_battery:
      <<: *customize
      friendly_name: "Fiddle Leaf Fig - Battery"
      
    sensor.plant_fiddle_leaf_fig_moisture:
      <<: *customize
      friendly_name: "Fiddle Leaf Fig - Moisture"
      
    sensor.plant_fiddle_leaf_fig_temperature:
      <<: *customize
      friendly_name: "Fiddle Leaf Fig - Temperature"
        
    sensor.plant_fiddle_leaf_fig_brightness:
      <<: *customize
      friendly_name: "Fiddle Leaf Fig - Brightness"
      
    sensor.plant_fiddle_leaf_fig_conductivity:
      <<: *customize
      friendly_name: "Fiddle Leaf Fig - Conductivity"
    
        
        
plant:
  fiddle_leaf_fig:
    sensors:
      moisture: sensor.plant_fiddle_leaf_fig_moisture
      battery: sensor.plant_fiddle_leaf_fig_battery
      temperature: sensor.plant_fiddle_leaf_fig_temperature
      conductivity: sensor.plant_fiddle_leaf_fig_conductivity
      brightness: sensor.plant_fiddle_leaf_fig_brightness
    min_moisture: 25
    max_moisture: 80
    min_battery: 15
    min_conductivity: 250
    min_temperature: 40
    max_temperature: 90

automation:
  - id: fiddle_leaf_fig_notify_problems
    alias: 'Fiddle Leaf Fig Notify of Problems'
    trigger:
    - entity_id: plant.fiddle_leaf_fig
      platform: state
      to: problem
    condition: []
    action:
    - data_template:
        message: "Fiddle Leaf Fig has an issue: {{ trigger.to_state.attributes.problem }}. Moisture: {{ trigger.to_state.attributes.moisture }}% Temp: {{ trigger.to_state.attributes.temperature }} Conductivity: {{ trigger.to_state.attributes.conductivity }}"
      service: notify.nick