################################################################
## Packages / peace_lily
################################################################

homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'plant_peace_lily'
      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false
        
    plant.peace_lily:
      <<: *customize
      friendly_name: Peace Lily
      
    sensor.plant_peace_lily:
      <<: *customize
      friendly_name: Peace Lily MQTT Sensor
      
    sensor.plant_peace_lily_battery:
      <<: *customize
      friendly_name: "Peace Lily - Battery"
      device_class: battery
      unit_of_measurement: '%'
      
    sensor.plant_peace_lily_moisture:
      <<: *customize
      friendly_name: "Peace Lily - Moisture"
      unit_of_measurement: '%'
      
    sensor.plant_peace_lily_temperature:
      <<: *customize
      friendly_name: "Peace Lily - Temperature"
      unit_of_measurement: '°F'
        
    sensor.plant_peace_lily_brightness:
      <<: *customize
      friendly_name: "Peace Lily - Brightness"
      unit_of_measurement: 'lux'
      
    sensor.plant_peace_lily_conductivity:
      <<: *customize
      friendly_name: "Peace Lily - Conductivity"
      unit_of_measurement: 'µS/cm'
    
        
        
plant:
  peace_lily:
    sensors:
      moisture: sensor.plant_peace_lily_moisture
      battery: sensor.plant_peace_lily_battery
      temperature: sensor.plant_peace_lily_temperature
      conductivity: sensor.plant_peace_lily_conductivity
      brightness: sensor.plant_peace_lily_brightness
    min_moisture: 25
    max_moisture: 80
    min_battery: 15
    min_conductivity: 250
    min_temperature: 40
    max_temperature: 90

sensor:
  - platform: mqtt
    state_topic: "twohunnidha/sensors/plants/peace_lily/"
    name: plant_peace_lily
    value_template: "{{ value_json.moisture }}"
    json_attributes:
      - battery
      - moisture
      - temperature
      - brightness
      - timestamp
      - conductivity
  - platform: template
    sensors:
      plant_peace_lily_battery:
        entity_id: sensor.plant_peace_lily
        value_template: "{{ states.sensor.plant_peace_lily.attributes.battery }}"
      plant_peace_lily_moisture:
        entity_id: sensor.plant_peace_lily
        value_template: "{{ states.sensor.plant_peace_lily.attributes.moisture }}"
      plant_peace_lily_temperature:
        entity_id: sensor.plant_peace_lily
        value_template: >
          {{ ((float(state_attr('sensor.plant_peace_lily', 'temperature')) * 9 /5)+32)|round(1) }}
      plant_peace_lily_brightness:
        entity_id: sensor.plant_peace_lily
        value_template: "{{ float(states.sensor.plant_peace_lily.attributes.brightness) }}"
      plant_peace_lily_conductivity:
        entity_id: sensor.plant_peace_lily
        value_template: "{{ float(states.sensor.plant_peace_lily.attributes.conductivity) }}"
        
automation:
  - id: peace_lily_notify_problems
    alias: 'Peace Lily Notify of Problems'
    trigger:
    - entity_id: plant.peace_lily
      platform: state
      to: problem
    condition: []
    action:
    - data_template:
        message: "Peace Lily has an issue: {{ trigger.to_state.state.attributes.problem }}. Moisture: {{ trigger.to_state.state.attributes.moisture }}% Temp: {{ trigger.to_state.state.attributes.temperature }} Conductivity: {{ trigger.to_state.state.attributes.conductivity }}"
      service: notify.nick