################################################################
## Packages / tiny_ivy
################################################################

homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'plant_tiny_ivy'
      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false
        
    plant.tiny_ivy:
      <<: *customize
      friendly_name: Tiny Ivy
      
    sensor.plant_tiny_ivy:
      <<: *customize
      friendly_name: Tiny Ivy MQTT Sensor
      
    sensor.plant_tiny_ivy_battery:
      <<: *customize
      friendly_name: "Tiny Ivy - Battery"
      device_class: battery
      unit_of_measurement: '%'
      
    sensor.plant_tiny_ivy_moisture:
      <<: *customize
      friendly_name: "Tiny Ivy - Moisture"
      unit_of_measurement: '%'
      
    sensor.plant_tiny_ivy_temperature:
      <<: *customize
      friendly_name: "Tiny Ivy - Temperature"
      unit_of_measurement: '°F'
        
    sensor.plant_tiny_ivy_brightness:
      <<: *customize
      friendly_name: "Tiny Ivy - Brightness"
      unit_of_measurement: 'lux'
      
    sensor.plant_tiny_ivy_conductivity:
      <<: *customize
      friendly_name: "Tiny Ivy - Conductivity"
      unit_of_measurement: 'µS/cm'
    
        
        
plant:
  tiny_ivy:
    sensors:
      moisture: sensor.plant_tiny_ivy_moisture
      battery: sensor.plant_tiny_ivy_battery
      temperature: sensor.plant_tiny_ivy_temperature
      conductivity: sensor.plant_tiny_ivy_conductivity
      brightness: sensor.plant_tiny_ivy_brightness
    min_moisture: 25
    max_moisture: 80
    min_battery: 15
    min_conductivity: 250
    min_temperature: 40
    max_temperature: 90

sensor:
  - platform: mqtt
    state_topic: "twohunnidha/sensors/plants/tiny_ivy/"
    name: plant_tiny_ivy
    value_template: "{{ value_json.moisture }}"
    json_attributes:
      - battery
      - moisture
      - temperature
      - brightness
      - timestamp
      - conductivity
  - platform: template
    sensors:
      plant_tiny_ivy_battery:
        entity_id: sensor.plant_tiny_ivy
        value_template: "{{ states.sensor.plant_tiny_ivy.attributes.battery }}"
      plant_tiny_ivy_moisture:
        entity_id: sensor.plant_tiny_ivy
        value_template: "{{ states.sensor.plant_tiny_ivy.attributes.moisture }}"
      plant_tiny_ivy_temperature:
        entity_id: sensor.plant_tiny_ivy
        value_template: >
          {{ ((float(state_attr('sensor.plant_tiny_ivy', 'temperature')) * 9 /5)+32)|round(1) }}
      plant_tiny_ivy_brightness:
        entity_id: sensor.plant_tiny_ivy
        value_template: "{{ float(states.sensor.plant_tiny_ivy.attributes.brightness) }}"
      plant_tiny_ivy_conductivity:
        entity_id: sensor.plant_tiny_ivy
        value_template: "{{ float(states.sensor.plant_tiny_ivy.attributes.conductivity) }}"
        
automation:
  - id: tiny_ivy_notify_problems
    alias: 'Tiny Ivy Notify of Problems'
    trigger:
    - entity_id: plant.tiny_ivy
      platform: state
      to: problem
    condition: []
    action:
    - data_template:
        message: "Tiny Ivy has an issue: {{ trigger.to_state.state.attributes.problem }}. Moisture: {{ trigger.to_state.state.attributes.moisture }}% Temp: {{ trigger.to_state.state.attributes.temperature }} Conductivity: {{ trigger.to_state.state.attributes.conductivity }}"
      service: notify.nick