################################################################
## Packages / tiny_ivy
################################################################

homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'plant_tiny_ivy'
      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false
        
    plant.tiny_ivy:
      <<: *customize
      friendly_name: Tiny Ivy
      
    sensor.plant_tiny_ivy_battery:
      <<: *customize
      friendly_name: "Tiny Ivy - Battery"
      
    sensor.plant_tiny_ivy_moisture:
      <<: *customize
      friendly_name: "Tiny Ivy - Moisture"
      
    sensor.plant_tiny_ivy_temperature:
      <<: *customize
      friendly_name: "Tiny Ivy - Temperature"
        
    sensor.plant_tiny_ivy_brightness:
      <<: *customize
      friendly_name: "Tiny Ivy - Brightness"
      
    sensor.plant_tiny_ivy_conductivity:
      <<: *customize
      friendly_name: "Tiny Ivy - Conductivity"
    
        
        
plant:
  tiny_ivy:
    sensors:
      moisture: sensor.plant_tiny_ivy_moisture
      battery: sensor.plant_tiny_ivy_battery
      temperature: sensor.plant_tiny_ivy_temperature
      conductivity: sensor.plant_tiny_ivy_conductivity
      brightness: sensor.plant_tiny_ivy_brightness
    min_moisture: 25
    max_moisture: 80
    min_battery: 15
    min_conductivity: 250
    min_temperature: 40
    max_temperature: 90

automation:
  - id: tiny_ivy_notify_problems
    alias: 'Tiny Ivy Notify of Problems'
    trigger:
    - entity_id: plant.tiny_ivy
      platform: state
      to: problem
    condition: []
    action:
    - data_template:
        message: "Tiny Ivy has an issue: {{ trigger.to_state.attributes.problem }}. Moisture: {{ trigger.to_state.attributes.moisture }}% Temp: {{ trigger.to_state.attributes.temperature }} Conductivity: {{ trigger.to_state.attributes.conductivity }}"
      service: notify.nick