################################################################
## Packages / zebra_plant
################################################################

homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'plant_zebra_plant'
      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false
        
    plant.zebra_plant:
      <<: *customize
      friendly_name: Zebra Plant
      
    sensor.plant_zebra_plant:
      <<: *customize
      friendly_name: Zebra Plant MQTT Sensor
      
    sensor.plant_zebra_plant_battery:
      <<: *customize
      friendly_name: "Zebra Plant - Battery"
      device_class: battery
      unit_of_measurement: '%'
      
    sensor.plant_zebra_plant_moisture:
      <<: *customize
      friendly_name: "Zebra Plant - Moisture"
      unit_of_measurement: '%'
      
    sensor.plant_zebra_plant_temperature:
      <<: *customize
      friendly_name: "Zebra Plant - Temperature"
      unit_of_measurement: '°F'
        
    sensor.plant_zebra_plant_brightness:
      <<: *customize
      friendly_name: "Zebra Plant - Brightness"
      unit_of_measurement: 'lux'
      
    sensor.plant_zebra_plant_conductivity:
      <<: *customize
      friendly_name: "Zebra Plant - Conductivity"
      unit_of_measurement: 'µS/cm'
    
        
        
plant:
  zebra_plant:
    sensors:
      moisture: sensor.plant_zebra_plant_moisture
      battery: sensor.plant_zebra_plant_battery
      temperature: sensor.plant_zebra_plant_temperature
      conductivity: sensor.plant_zebra_plant_conductivity
      brightness: sensor.plant_zebra_plant_brightness
    min_moisture: 25
    max_moisture: 80
    min_battery: 15
    min_conductivity: 250
    min_temperature: 40
    max_temperature: 90

sensor:
  - platform: mqtt
    state_topic: "twohunnidha/sensors/plants/zebra_plant/"
    name: plant_zebra_plant
    value_template: "{{ value_json.moisture }}"
    json_attributes:
      - battery
      - moisture
      - temperature
      - brightness
      - timestamp
      - conductivity
  - platform: template
    sensors:
      plant_zebra_plant_battery:
        entity_id: sensor.plant_zebra_plant
        value_template: "{{ states.sensor.plant_zebra_plant.attributes.battery }}"
      plant_zebra_plant_moisture:
        entity_id: sensor.plant_zebra_plant
        value_template: "{{ states.sensor.plant_zebra_plant.attributes.moisture }}"
      plant_zebra_plant_temperature:
        entity_id: sensor.plant_zebra_plant
        value_template: >
          {{ ((float(state_attr('sensor.plant_zebra_plant', 'temperature')) * 9 /5)+32)|round(1) }}
      plant_zebra_plant_brightness:
        entity_id: sensor.plant_zebra_plant
        value_template: "{{ float(states.sensor.plant_zebra_plant.attributes.brightness) }}"
      plant_zebra_plant_conductivity:
        entity_id: sensor.plant_zebra_plant
        value_template: "{{ float(states.sensor.plant_zebra_plant.attributes.conductivity) }}"
        
automation:
  - id: zebra_plant_notify_problems
    alias: 'Zebra Plant Notify of Problems'
    trigger:
    - entity_id: plant.zebra_plant
      platform: state
      to: problem
    condition: []
    action:
    - data_template:
        message: "Zebra Plant has an issue: {{ trigger.to_state.attributes.problem }}. Moisture: {{ trigger.to_state.attributes.moisture }}% Temp: {{ trigger.to_state.attributes.temperature }} Conductivity: {{ trigger.to_state.attributes.conductivity }}"
      service: notify.nick