#### PLANTS - desert rose ####

- platform: mqtt
  state_topic: "twohunnidha/sensors/plants/desert_rose/"
  name: plant_desert_rose
  value_template: "{{ value_json.moisture }}"
  json_attributes:
    - battery
    - moisture
    - temperature
    - brightness
    - timestamp
    - conductivity

- platform: template
  sensors:
    plant_desert_rose_battery:
      friendly_name: "Desert Rose - Battery"
      entity_id: sensor.plant_desert_rose
      value_template: "{{ states.sensor.plant_desert_rose.attributes.battery }}"
      device_class: battery
      unit_of_measurement: '%'
    plant_desert_rose_moisture:
      friendly_name: "Desert Rose - Moisture"
      entity_id: sensor.plant_desert_rose
      unit_of_measurement: '%'
      value_template: "{{ states.sensor.plant_desert_rose.attributes.moisture }}"
    plant_desert_rose_temperature:
      friendly_name: "Desert Rose - Temperature"
      entity_id: sensor.plant_desert_rose
      unit_of_measurement: 'F'
      value_template: >
        {{ ((float(state_attr('sensor.plant_desert_rose', 'temperature')) * 9 /5)+32)|round(1) }}
    plant_desert_rose_brightness:
      friendly_name: "Desert Rose - Brightness"
      entity_id: sensor.plant_desert_rose
      value_template: "{{ states.sensor.plant_desert_rose.attributes.brightness }}"
    plant_desert_rose_conductivity:
      friendly_name: "Desert Rose - Conductivity"
      entity_id: sensor.plant_desert_rose
      unit_of_measurement: 'µS/cm'
      value_template: "{{ states.sensor.plant_desert_rose.attributes.conductivity }}"
      