#### PLANTS - lemon_verbena ####

- platform: mqtt
  state_topic: "twohunnidha/sensors/plants/lemon_verbena/"
  name: plant_lemon_verbena
  value_template: "{{ value_json.moisture }}"
  json_attributes:
    - battery
    - moisture
    - temperature
    - brightness
    - timestamp
    - conductivity

- platform: template
  sensors:
    plant_lemon_verbena_battery:
      friendly_name: "Lemon Verbena - Battery"
      entity_id: sensor.plant_lemon_verbena
      value_template: "{{ states.sensor.plant_lemon_verbena.attributes.battery }}"
      device_class: battery
      unit_of_measurement: '%'
    plant_lemon_verbena_moisture:
      friendly_name: "Lemon Verbena - Moisture"
      entity_id: sensor.plant_lemon_verbena
      unit_of_measurement: '%'
      value_template: "{{ states.sensor.plant_lemon_verbena.attributes.moisture }}"
    plant_lemon_verbena_temperature:
      friendly_name: "Lemon Verbena - Temperature"
      entity_id: sensor.plant_lemon_verbena
      unit_of_measurement: '°F'
      value_template: >
        {{ ((float(state_attr('sensor.plant_lemon_verbena', 'temperature')) * 9 /5)+32)|round(1) }}
    plant_lemon_verbena_brightness:
      friendly_name: "Lemon Verbena - Brightness"
      entity_id: sensor.plant_lemon_verbena
      value_template: "{{ states.sensor.plant_lemon_verbena.attributes.brightness }}"
    plant_lemon_verbena_conductivity:
      friendly_name: "Lemon Verbena - Conductivity"
      entity_id: sensor.plant_lemon_verbena
      unit_of_measurement: 'µS/cm'
      value_template: "{{ states.sensor.plant_lemon_verbena.attributes.conductivity }}"