#### PLANTS - peace_lily ####

- platform: mqtt
  state_topic: "twohunnidha/sensors/plants/peace_lily/"
  name: plant_peace_lily
  value_template: "{{ value_json.moisture }}"
  json_attributes:
    - battery
    - moisture
    - temperature
    - brightness
    - timestamp
    - conductivity

- platform: template
  sensors:
    plant_peace_lily_battery:
      friendly_name: "Peace Lily - Battery"
      entity_id: sensor.plant_peace_lily
      value_template: "{{ states.sensor.plant_peace_lily.attributes.battery }}"
      device_class: battery
      unit_of_measurement: '%'
    plant_peace_lily_moisture:
      friendly_name: "Peace Lily - Moisture"
      entity_id: sensor.plant_peace_lily
      unit_of_measurement: '%'
      value_template: "{{ states.sensor.plant_peace_lily.attributes.moisture }}"
    plant_peace_lily_temperature:
      friendly_name: "Peace Lily - Temperature"
      entity_id: sensor.plant_peace_lily
      unit_of_measurement: 'F'
      value_template: >
        {{ ((float(state_attr('sensor.plant_peace_lily', 'temperature')) * 9 /5)+32)|round(1) }}
    plant_peace_lily_brightness:
      friendly_name: "Peace Lily - Brightness"
      entity_id: sensor.plant_peace_lily
      value_template: "{{ states.sensor.plant_peace_lily.attributes.brightness }}"
    plant_peace_lily_conductivity:
      friendly_name: "Peace Lily - Conductivity"
      entity_id: sensor.plant_peace_lily
      unit_of_measurement: 'µS/cm'
      value_template: "{{ states.sensor.plant_peace_lily.attributes.conductivity }}"
      