#### PLANTS - zebra plant ####

## mqtt sensor for miflora
- platform: mqtt
  state_topic: "twohunnidha/sensors/plants/zebra_plant/"
  name: plant_zebra_plant
  value_template: "{{ value_json.moisture }}"
  json_attributes:
    - battery
    - moisture
    - temperature
    - brightness
    - timestamp
    - conductivity
    
## template sensors for transforming mqtt data
- platform: template
  sensors:
    plant_zebra_plant_battery:
      friendly_name: "Zebra Plant - Battery"
      entity_id: sensor.plant_zebra_plant
      value_template: "{{ states.sensor.plant_zebra_plant.attributes.battery }}"
      device_class: battery
      unit_of_measurement: '%'
    plant_zebra_plant_moisture:
      friendly_name: "Zebra Plant - Moisture"
      entity_id: sensor.plant_zebra_plant
      unit_of_measurement: '%'
      value_template: "{{ states.sensor.plant_zebra_plant.attributes.moisture }}"
    plant_zebra_plant_temperature:
      friendly_name: "Zebra Plant - Temperature"
      entity_id: sensor.plant_zebra_plant
      unit_of_measurement: '°F'
      value_template: >
        {{ ((float(state_attr('sensor.plant_zebra_plant', 'temperature')) * 9 /5)+32)|round(1) }}
    plant_zebra_plant_brightness:
      friendly_name: "Zebra Plant - Brightness"
      entity_id: sensor.plant_zebra_plant
      value_template: "{{ states.sensor.plant_zebra_plant.attributes.brightness }}"
    plant_zebra_plant_conductivity:
      friendly_name: "Zebra Plant - Conductivity"
      entity_id: sensor.plant_zebra_plant
      unit_of_measurement: 'µS/cm'
      value_template: "{{ states.sensor.plant_zebra_plant.attributes.conductivity }}"