################################################################
## Packages / Garage Door
################################################################

homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'garage_door'
      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false
        
    light.x10_garage_door_relay:
      <<: *customize
      friendly_name: "Garage Door X10 Relay"
      hidden: true
      icon: mdi:light-switch
      
    switch.garage_door_button:
      <<: *expose
      friendly_name: "Garage Door"
      icon: mdi:light-switch
      
    script.garage_door_button_turn_on:
      <<: *expose
      friendly_name: "Garage Door"
      icon: mdi:light-switch
      
    binary_sensor.garage_door:
      <<: *customize
      friendly_name: "Garage Door Open?"
      


light:
  - platform: x10rf
    devices:
      - id: b3
        name: x10_garage_door_relay
        
switch:
  - platform: template
    switches:
      garage_door_button:
        entity_id: light.x10_garage_door_relay
        value_template: "{{ false }}"
        turn_on:
          service: script.turn_on
          data:
            entity_id: script.garage_door_button_turn_on
        turn_off:
          service: logbook.log
          data_template:
            name: Garage Door Button
            message: is turned off
            entity_id: switch.garage_door_button
            domain: switch
            
script:
  garage_door_button_turn_on:
    sequence:
      - service: light.turn_on
        data:
          entity_id: light.x10_garage_door_relay
      - delay: '00:00:02'
      - service: homeassistant.turn_off
        data:
          entity_id: switch.garage_door_button
            
binary_sensor:
  - platform: template
    sensors:
      garage_door:
        friendly_name: "Garage Door"
        device_class: garage_door
        value_template: "{{ states('sensor.vision_zg8101_garage_door_detector_alarm_level')|int == 255 }}"
        
sensor:
  - platform: template
    sensors:
      garage_door_status:
        friendly_name: "Garage Door Status"
        value_template: >-
          {% if states('sensor.vision_zg8101_garage_door_detector_alarm_level')|int == 255 and states('sensor.vision_zg8101_garage_door_detector_burglar')|int == 2 %}
            opening
          {% elif states('sensor.vision_zg8101_garage_door_detector_alarm_level')|int == 0 and states('sensor.vision_zg8101_garage_door_detector_burglar')|int == 254 %}
            closing
          {% elif states('sensor.vision_zg8101_garage_door_detector_alarm_level')|int == 0 and states('sensor.vision_zg8101_garage_door_detector_burglar')|int == 2 %}
            closed
          {% elif states('sensor.vision_zg8101_garage_door_detector_alarm_level')|int == 255 and states('sensor.vision_zg8101_garage_door_detector_burglar')|int == 254 %}
            open
          {% endif %}
          