- platform: template
  lights:
    backyard_flood_lights:
      friendly_name: "Backyard Flood Lights"
      level_template: '{{ 255 if is_state("switch.inovelli_nzw30_onoff_switch_switch_2", "on") else 0 }}' 
      value_template: '{{ is_state("switch.inovelli_nzw30_onoff_switch_switch_2", "on") }}'
      turn_on:
        service: switch.turn_on
        entity_id: switch.inovelli_nzw30_onoff_switch_switch_2
      turn_off:
        service: switch.turn_off
        entity_id: switch.inovelli_nzw30_onoff_switch_switch_2
      set_level:
        service_template: switch.turn_'{{ "off" if brightness == 0 else "on" }}'
        entity_id: switch.inovelli_nzw30_onoff_switch_switch_2