homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'zwift'
        
sensor:
  - platform: zwift
    username: !secret zwift_username
    password: !secret zwift_password
    players:
      - 803962
  