- alias: "Git: Commit Files on Local Config Changes"
  trigger:
    platform: event
    event_type: folder_watcher
    event_data:
      event_type: modified
  action:
    service: notify.nick
    data_template:
      title: "A file was modified!"
      message: "{{ trigger.event.data.file }} in {{ trigger.event.data.folder }}"