- platform: template
  sensors:
    device_motion_backyard_north_battery:
      friendly_name: "Motion - Backyard (North) - Battery"
      entity_id: zwave.vision_zp3102_pir_motion_sensor
      device_class: battery
      unit_of_measurement: '%'
      value_template: "{{ states.zwave.vision_zp3102_pir_motion_sensor.attributes.battery_level }}"