- platform: template
  sensors:
    device_motion_front_yard_south_battery:
      friendly_name: "Motion - Front Driveway (Battery)"
      entity_id: zwave.vision_zp3102_pir_motion_sensor_4
      device_class: battery
      unit_of_measurement: '%'
      value_template: "{{ states.zwave.vision_zp3102_pir_motion_sensor_4.attributes.battery_level }}"