- platform: template
  sensors:
    device_motion_indoor_foyer_battery:
      friendly_name: "Motion - Indoor Foyer - Battery"
      entity_id: zwave.vision_zp3111_multisensor_4in1
      device_class: battery
      unit_of_measurement: '%'
      value_template: "{{ states.zwave.vision_zp3111_multisensor_4in1.attributes.battery_level }}"