homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'copper_wire_string_lights'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false
        
    switch.rm_mini_copper_wire_string_lights:
      hidden: true
    
    light.copper_wire_string_lights:
      <<: *expose
      friendly_name: "Copper Wire String Lights"
      comm_protocol: "infrared"
        
light:
  - platform: template
    lights:
      copper_wire_string_lights:
        value_template: '{{ is_state("switch.rm_mini_copper_wire_string_lights", "on") }}'
        turn_on:
          service: switch.turn_on
          entity_id: switch.rm_mini_copper_wire_string_lights
        turn_off:
          service: switch.turn_off
          entity_id: switch.rm_mini_copper_wire_string_lights