homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'dining_room_chandelier'
    
    light.z_wave_products_inc_wd100_level:
      <<: *customize
      friendly_name: "Dining Room Chandelier"
        