homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'backyard_amplifier'
        
    light.outside_amplifier_28:
      <<: *customize
      hidden: true
    
    switch.backyard_amplifier:
      <<: *customize
      friendly_name: "Backyard Amplifier"
      comm_protocol: "infrared"

switch:
  - platform: template
    switches:
      backyard_amplifier:
        value_template: "{{ is_state('light.outside_amplifier_28', 'on') }}"
        turn_on:
          service: light.turn_on
          data:
            entity_id: light.outside_amplifier_28
        turn_off:
          service: light.turn_off
          data:
            entity_id: light.outside_amplifier_28